version: '3'

services: 
  tensorflow-serving:
    build: 
      context: ./
      dockerfile: Dockerfile.serving
    command:
      - '--model_config_file=/models/models.conf'
    expose: 
      - 8500-8501
    depends_on: 
      - web
      
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    volumes: 
      - sql_data:/app/database
    command: gunicorn --bind 0.0.0.0:5000 wsgi
    expose:
      - 5000
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile.nginx
    ports:
      - 1337:80

volumes:
  sql_data: